all:
  hosts:
    192.168.40.136:
      ansible_user: jenkins # Remplacez par l'utilisateur SSH de la machine distante
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa  # Chemin vers la clé privée SSH
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  # Option pour ignorer la vérification de la clé hôte
